### ISSUE TITLE
Read RX Frequency Error in LR1120

### ISSUE THREAD

**Issue by Chun-Yi-Liao** [Lora-net/SWDR001#2]
Hi 
In sx1262/1 there are registers return receive frequency error. Please see the Semtech code from line 844 to 854 in the link below. https://os.mbed.com/teams/Semtech/code/SX126xLib/file/c6ef863d0b07/sx126x.cpp/
Is there a similar way to read the received frequency error in LR1120? If yes, what are the register addresses to read the RX frequency error? 
Thanks.

**Comment by opeyrard** [comment]
This is not available on LR1120 drivers.
