### ISSUE TITLE
bug - lr1120 returns false Command Status indicator

### ISSUE THREAD

**Issue by zafersn** [Lora-net/SWDR001#3]
Hi @matthieuantoine 

I'm not sure if it is a bug or not. but seems a bug or something is weird.  this error was the first time I came across it,

sequentially, I am executing these commands; 

1. lr11xx_wifi_scan_time_limit 
2. lr11xx_wifi_get_nb_results 

lr11xx_wifi_get_nb_results this command sometimes returns 0 or 13(hex) in nbresult byte. I'm sure it should be 0  and whenever I read 13 and status byte was always CMD_PERR (3) and I can understand that nbresult byte value is wrong and must ignore it. However, one time I got the status byte 5 with nbresults 13. Now I am really confused. 

here is a write command output for nb result

![image](https://user-images.githubusercontent.com/13236364/203825655-bf893f9a-fcac-4aaf-bb4f-61fd0446c339.png)

here is a read command output below for nb result. as seen in the first byte the status indicator shows The last command was processed successfully. but I got 13 as nbresult byte. 

I'm wondering why I get sometimes 13 sometimes 0. there is no problem with the status indicator when I got nbresult byte as 0.

![image](https://user-images.githubusercontent.com/13236364/203825874-c35f6a79-bb9e-4227-9903-3061f5bc83d6.png)

Cheers!

**Comment by opeyrard** [comment]
Could you please double check with the latest release and let us know if the issue remains ?
Many thanks

**Comment by opeyrard** [comment]
Issue closed as there is no more activity.
