### ISSUE TITLE
own LoRa Cloud server

### ISSUE THREAD

**Issue by edbek** [Lora-net/SWDR001#4]
Data from satellites and WiFi are transferred to a special LoRa Cloud server to obtain the location.
Is it possible to build your own server based on this data? Is this data public?

**Comment by richard-at-semtech** [comment]
The format of the data that is returned from the LoRa Edge WiFi measurement is public and specified in the users manual for the chip (available at [semtech.com](https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/RQ000001DmRJ/.BD3tRRoM1xW5W1VpTVe2rkizt6u76_g7xowpMoNq6U)). Where that data is directed is in complete control of the device application designer. This WiFi data can be directed to any server for mapping the WiFi data into location solutions.  Semtech offers examples of how to send this WiFi data via LoRaWAN to the LoRa Cloud server to process it into a location solution. Data from satellites is in a proprietary format and must be processed by [LoRa Cloud](https://www.loracloud.com) or the service provided by [AWS IoT Core Device Location Services](https://aws.amazon.com/blogs/iot/how-to-get-started-with-the-new-aws-iot-core-device-location-service/).

**Comment by opeyrard** [comment]
Based on previous response, issue can be closed.
